using Microsoft.AspNetCore.Mvc;
using motoShop.Data;
using System.Collections.Generic;
using System.Linq;

namespace motoShop.Controllers
{
    public class StatisticsController : Controller
    {
        private readonly motoShopContext _context;

        public StatisticsController(motoShopContext context)
        {
            _context = context;
        }

        // GET: Statistics
        public IActionResult Index()
        {
            return View();
        }

        // Get gross income generated by branch -----> from orders
        [HttpGet]
        public JsonResult TotalIncomeByBranch()
        {
            //get all products in orders
            var query = from order in _context.Order
                        join item in _context.ShoppingCartItems on order.ShoppingCartId equals item.ShoppingCartId
                        select item.Product;

            //group them by branch and sums the total income of each branch
            var result = query.GroupBy(o => o.Branch.BranchName).Select( o => new
            {
                Income = o.Sum(order =>order.UnitsSold * order.Price),
                Name = o.Key
            });

            return Json(result);
        }

        //Get total number of items sold by Product Type
        [HttpGet]
        public ActionResult TotalOrdersByProductType()
        {

            //get all products in orders
            var query = from order in _context.Order
                        join item in _context.ShoppingCartItems on order.ShoppingCartId equals item.ShoppingCartId
                        select item.Product;

            //group them by branch and sums the total income of each branch
            var result = query.GroupBy(o => o.Type).Select(o => new
            {
                Amount = o.Sum(order => order.UnitsSold),
                Name = o.Key.ToString()
            });
            return Json(result);
        }
    }
}
